config/routes.rb
require "sidekiq/web"
require "sidekiq-scheduler/web"

Rails.application.routes.draw do
  resources :mentees
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username),
      ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"])) &
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password),
        ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"]))
  end
  mount Sidekiq::Web => "/sidekiq"

  # Defines the root path route ("/")
  # root "posts#index"

  resources :mentors
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/mentee.rb
class Mentee < ApplicationRecord
  validates :email, presence: true, uniqueness: true

  validates :name, presence: true
end

app/models/mentor.rb
class Mentor < ApplicationRecord
  validates :email, presence: true, uniqueness: true

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mentees_controller.rb
class MenteesController < ApplicationController
  def index
    @mentees = Mentee.all
  end

  def show
    @mentee = Mentee.find(params[:id])
  end

  def new
    @mentee = Mentee.new
  end

  def create
    @mentee = Mentee.new(name: "Stefany", email: "stefany@gmail.com")
    if @mentee.save
      redirect_to @mentee
    else
      render :new, status: :unprocessable_entity
    end
  end
end

app/controllers/mentors_controller.rb
class MentorsController < ApplicationController
  def index
    @mentors = Mentor.all
  end

  def new
    @mentor = Mentor.new
  end

  def create
    @mentor = Mentor.new(mentor_params)

    @mentor.save
    redirect_to @mentor
  end

  def show
    @mentor = Mentor.find(params[:id])
  end

  private

  def mentor_params
    params.require(:mentor).permit(:name, :email, :url, :bio)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mentees_helper.rb
module MenteesHelper
end

app/helpers/mentors_helper.rb
module MentorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mentorship</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mentees/index.html.erb
<h1>Hello</h1>
<ul>
  <% @mentees.each do |mentee|%>
    <li>
      <a href="/mentees/<%= mentee.id %>">
      <%= mentee.name%>
    </li>
  <% end %>
</ul>

app/views/mentees/new.htmal.erb
<h1>Mentee</h1>

<%= form_with model: @mentee do |mentee| %>
  <div>
    <%= form_label :name%><br>
    <%= form_text_field :name%>
  </div>

  <div>
    <%= form_label :email%><br>
    <%= form_text_field :name%>
  </div>
<%end%>

app/views/mentees/show.html.erb
<h1><%= @mentee.name%></h1>
<h2><%= @mentee.email%></h2>

app/views/mentors/index.erb
<h1>Lista de mentores!</h1>

<table>
  <% if @mentors.size > 0 %>
   <tr>
   <th>Nome</th>
   <th>Bio</th>
  </tr>
  <%@mentors.map do |mentor|%>
  <tr>
    <td><%=mentor.name%></td>
    <td><%=mentor.bio%></td>  
  <%end%>
  <% else %>
    <tr>
      <td>Não temos mentores cadastrados!</td>
    </tr>
  <%end%>
  <%%>
</tr>

</table>

app/views/mentors/index.html.erb
<h1>Lista de mentores!</h1>

<table>
  <% if @mentors.size > 0 %>
    <tr>
    <th>Nome</th>
    <th>Bio</th>
  </tr>
  <%@mentors.map do |mentor|%>
  <tr>
    <td><%=mentor.name%></td>
    <td><%=mentor.bio%></td>
  <%end%>
  <% else %>
    <tr>
      <td>Não temos mentores cadastrados!</td>
    </tr>
  <%end%>
  <%%>
</tr>

</table>

app/views/mentors/new.html.erb
<h1>Novo Mentor</h1>

<%= form_with(model: @mentor, local: true) do |form| %>
 <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :mentor_name %>
 </div>

 <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email, id: :mentor_email %>
 </div>

 <div class="field">
    <%= form.label :url %>
    <%= form.url_field :url, id: :mentor_url %>
 </div>

 <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio, id: :mentor_bio %>
 </div>

 <div class="actions">
    <%= form.submit %>
 </div>
<% end %>

app/views/mentors/show.html.erb
<h1><%= @mentor.name %></h1>

<p>Email: <%= @mentor.email %></p>
<p>URL: <%= @mentor.url %></p>
<p>Biografia: <%= @mentor.bio %></p>

<p>
  <%= link_to 'Editar', edit_mentor_path(@mentor), class: 'btn btn-primary' %> |
  <%= link_to 'Voltar', mentors_path, class: 'btn btn-secondary' %>
</p>